### ISSUE TITLE
run: support executing scripts with shebang notation

### ISSUE THREAD

**Issue by achille-roussel** [stealthrocket/dispatch#13]
I tried running a Python script that I made executable and was using this code:

```python
#!/usr/bin/env python3
import dispatch

...
```
And got this error message:
```
Error: failed to invoke command './main.py': fork/exec ./main.py: no such file or directory
```

It would be great to support it, I imagine this means running the command in a shell? (maybe consulting the `SHELL` environment variable)

**Comment by chriso** [comment]
This is working as expected.

**Comment by achille-roussel** [comment]
Thanks for double-checking @chriso, I must have done something wrong.
