### ISSUE TITLE
Don't fail when queue is empty

### ISSUE THREAD

**Issue by Pryz** [stealthrocket/dispatch#3]
When there is nothing in the bridge queue, the client will show a warning:
```
2024/04/11 21:34:06 WARN failed to contact Dispatch API (https://bridge.dev.dispatch.run): Get "https://bridge.dev.dispatch.run/sessions/099e4f53-db99-4c5b-a4e9-26e4f1fa3472": stream error: stream ID 1; INTERNAL_ERROR; received from peer
```
We should either move this warning behind a debug flag or handle it gracefully.

**Comment by chriso** [comment]
This indicates that the connection is being closed somewhere before the long polling CLI receives the expected 504 response from upstream.
