### ISSUE TITLE
login: automate creation of verification key during login

### ISSUE THREAD

**Issue by achille-roussel** [stealthrocket/dispatch#6]
After logging in, attempts to get the current verification key gives this error:
```
$ dispatch verification get
Error: Key not found. Use `dispatch verification rollout` to create the first key.
```
We could avoid exposing the user to this error if we automated the creation of the verification key.

**Comment by chriso** [comment]
See https://github.com/stealthrocket/dispatch/issues/7#issuecomment-2058179030.
